import "./globals.css";
import type { Metadata } from "next";
import ThemeProvider from "@/components/theme-provider";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Scalio Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
